modLoader = "javafml"
loaderVersion = "[40,41)"
issueTrackerURL = "https://github.com/impleri/item-skills/issues"
license = "MIT"

[[mods]]
modId = "itemskills"
version = "${version}"
displayName = "Item Skills"
authors = "impleri"
description = '''
A library mod that exposes KubeJS methods to restrict crafting recipes and players' ability to pick up restricted items.
'''
#logoFile = ""

[[dependencies.itemskills]]
modId = "curios"
mandatory = false
versionRange = "[1.18.2-5.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemskills]]
modId = "jei"
mandatory = false
versionRange = "[9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemskills]]
modId = "playerskills"
mandatory = true
versionRange = "[1.0.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemskills]]
modId = "forge"
mandatory = true
versionRange = "[40,41)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemskills]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemskills]]
modId = "architectury"
mandatory = true
versionRange = "[4.0,)"
ordering = "AFTER"
side = "BOTH"
