name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
      - synchronize
      - opened
    branches:
      - main

jobs:
  build:
    uses: impleri/automatic-skills/.github/workflows/build.yml@main

  bump:
    uses: impleri/automatic-skills/.github/workflows/version-bump.yml@main
    needs: build
    permissions:
      contents: write
    if: github.event.pull_request.merged == true

  publish:
    uses: impleri/automatic-skills/.github/workflows/publish.yml@main
    needs: bump
    permissions:
      contents: write
    secrets:
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_TOKEN }}
      modrinth-id: ${{ secrets.MODRINTH_ID }}
      modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
      curseforge-id: ${{ secrets.CURSEFORGE_ID }}
      curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
